### PR TITLE
WIP: calculate line number width using static values

### PR DESCRIPTION
**Pull request by KevinBatdorf**
This updates how the line number are computed, using a simple formula (`fontSize` * `highestLineNumber` * `0.6` ratio) to estimate a "good enough" width.

Previously it would get the exact width, which fails when two users using differing zoom levels edit a post. Regardless, as was pointed out to me, it shouldn't be reliant on the font size of the user editing it, but the font size of the browser (and user viewing the page).

### CODE REVIEW

**Comment by KevinBatdorf** [comment]
Hey @rene-hermenau Whenever you have time could you try this one out? No rush or anything. Hoping this approach works but might need to tweak it a bit more.

**Comment by rene-hermenau** [comment]
Sure thing @KevinBatdorf 
Do you have a quick install guide about how to build the dist package for testing it?

**Comment by rene-hermenau** [comment]
You can send it to admin [at] xsimulator.net if you don't want to make it publically available here.

**Comment by KevinBatdorf** [comment]
Ah, I'm sorry. I meant to add instructions. Easiest would be to just use the pre-built zip.

Go here and click the top one:
https://github.com/KevinBatdorf/code-block-pro/actions/workflows/build-production-zip.yml

Then download the zip:

CleanShot 2023-09-18 at 09 09 56

**Comment by rene-hermenau** [comment]
It seems to work for a new post with new code blocks.
Changing the dpi and zoom does not change anymore all blocks.🎉
The lineNumberWidth does not appear anymore.

As you probably aware of, It does not work with existing code blocks, where lineNumberWidth is still in the block code. Then that value is still updated in all blocks. If you could remove later (when this PR is ready to merge) that Attribute from existing blocks after saving an existing block page it would be helpful.
Otherwise, if you say its save to delete, I will run a manual regex on the blocks content to get rid of it.

Thanks for getting on to this @KevinBatdorf

**Comment by rene-hermenau** [comment]
It's only happening on Save Post and then comparing the revisions of two updates. At least, only then I am able to compare two revisions.
That's the original page: https://wp-staging.com/docs/actions-and-filters/

Attached you'll find the block source of the page. So you could easily reproduce it with the original page code.
[actions-and-filters.txt](https://github.com/KevinBatdorf/code-block-pro/files/12673920/actions-and-filters.txt)

I've also created a video for you with each step: 
https://monosnap.com/file/Du989zazzHaXE9hhwrmjHfWOAIWClg

**Comment by KevinBatdorf** [comment]
I tried out the code sample. I think this is how I expect it to work. 

Is it only the one time though, right? or is it adjusting every time going zoomed 150% back to 100%, etc over and over forever? It should only be a one time update to bring it in line with the "real" font size.

Is the concern about that one revision? I could possibly add some check to only update it if the block is focused, which would prevent old pages, but what's the implication? Just having the needless revision in the database?

**Comment by rene-hermenau** [comment]
> Is it only the one time though, right?

No, it happens always. 

> or is it adjusting every time going zoomed 150% back to 100%, etc over and over forever?

Yes, over and over!

E.g Bob uses another zoom size like 150% and Peter uses 100%.

Once, Bob does a change, Peter will see that **all** blocks were modified so Peter can not do a line by line review what Bob actually changed.

Then Peter does a change to the same document and again all blocks  line-number-width will be modified.

I am starting to think as long as the line-number-width is always modifed for each zoom factor and included in each doc block this is not solveable.

**Comment by KevinBatdorf** [comment]
I'll look into it some more. I'm out of town this weekend but will the following week. I thought I tried that and couldn't reproduce it, but maybe I missed something. 

> It seems to work for a new post with new code blocks.
> Changing the dpi and zoom does not change anymore all blocks.

But it works perfectly on new pages/blocks you make? Or is there still something going on here? That's where it gets confusing, because there's not much difference form a new page and an existing one. Any more hints here will help me out though.

> I am starting to think as long as the line-number-width is always modifed for each zoom factor and included in each doc block this is not solveable.

Maybe, but I'll figure something out because I don't think it's acceptable to have this sort of quirky behavior anyway

**Comment by rene-hermenau** [comment]
> But it works perfectly on new pages/blocks you make?

I tried it again and I have to withdraw this statement. It does not work, even with a new popst. 
For an unknown reason `lineNumberWidth` did not exist in my initial test when I've told you that it worked. 

Now, when I create a new post, `lineNumberWidth` will be added to source and the quirky behavior happens again. At least it fails consistently now:)
Enjoy your weekend and have a good one.😀

**Comment by KevinBatdorf** [comment]
Hey! So I think I may have a good solution now. Instead of using the computed width this now uses the fontSize * the length of the longest line number * a width ratio of 0.6, which I think works well.

It should _not_ cause a block validation error, so if you see one then let me know. It should require a single update though to each post, as i've added a "highestLineNumber" attribute that is used later for the calculation

**Comment by KevinBatdorf** [comment]
> Seems to happen because there is no parent folder with the plugin name in the zip file. I've uploaded code-block-pro(1).zip to my site;-)

Ah, interesting. Let me see if Ic an do something about that. The workflow file ([here](https://github.com/KevinBatdorf/code-block-pro/blob/main/.github/workflows/build-production-zip.yml#L24)) has it named but maybe it's not working properly or something. 

> So, do we need to remove lineNumbersWidth from existing code blocks to see it working or create a new code block?

I think it will stay there in existing blocks (if I auto-remove it, it will cause a block validation error), but new blocks won't have it. Is that accurate? In the existing blocks it just will exist but never be used for anything. 

> I can see the fontSize value and its identical between each revision.

What should be new is `highestLineNumber` for existing blocks.

Thanks again for testing

**Comment by rene-hermenau** [comment]
Mhh, I definately installed the new version (two times) and cleared our object cache, etc. but highestLineNumber is not added and it just works as before without any change.

Edit: The created zip file from the Artifacts does not contain the changes you did: 
https://github.com/KevinBatdorf/code-block-pro/actions/runs/6448590429
https://github.com/KevinBatdorf/code-block-pro/suites/17005675308/artifacts/971250041

I downloaded that one:
https://github.com/KevinBatdorf/code-block-pro/actions/runs/6448590429

I looked into /src/editor/Edit.tsx 

Feel free to verify this and send me a link to a version with that change and I will do a test.

**Comment by KevinBatdorf** [comment]
Sorry about that! That run was for another branch "add-fixed-line-numbers" that I was working on to make the front end line numbers fixed with a horizontal scroll. I was experimenting with it but putting that on hold for now as it requires supporting a lot of edge cases

I guess the best way to get the build artifact is from the PR directly. 

CleanShot 2023-10-10 at 11 58 18


Here's the link though: https://github.com/KevinBatdorf/code-block-pro/actions/runs/6471674272?pr=245

**Comment by rene-hermenau** [comment]
Fantastic! Now we're finally getting somewhere:)
I was not able to break it and it simply works. I will keep that version active on our system to see if we run into any issues but this looks superb.

As a small thanksgiving I will add https://code-block-pro.com/ as a partner link to wp-staging.com
It's created with so much passion that it deserves much more installs;) Of course only if you are interested and are ok with it. 

It would look like:
image

I can not promise how long I can place that link but its without any obligations. it's looking very cool and your plugin suits to us from what it does.

**Comment by rene-hermenau** [comment]
Please write to me to rene [at] wp[-]staging.com for discussing details about this and not to get more offtopic here..

**Comment by KevinBatdorf** [comment]
That's great! I may just make a release today then actually. I'll send an email in a bit.

**Pull request merged**
